edition = "2024"

fn_args_layout = "Vertical"
fn_params_layout = "Vertical"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
reorder_impl_items = true
unstable_features = true
